# CDS-visual1 - Introduction to Python (Continued)

In [3]:
#Creating a snippet of text
text_snippet = "It was the best of times, it was the worst of times"

In [4]:
# Når noget har runde parantes så er det en funktion
print()

In [5]:
# Når man laver et punktum efter sin variable, så kommer der flere muligheder for metoder at kunne bruges
text_snippet.upper()

'IT WAS THE BEST OF TIMES, IT WAS THE WORST OF TIMES'

In [6]:
text_snippet.lower()

'it was the best of times, it was the worst of times'

In [7]:
#En handy metode at kunne til language analytics - Split alle ordene op fra hinanden i linjer
text_snippet.split()

['It',
 'was',
 'the',
 'best',
 'of',
 'times,',
 'it',
 'was',
 'the',
 'worst',
 'of',
 'times']

In [8]:
#Man kan sige præcis hvor man vil splitte, men standard er mellemrum. 
text_snippet.split(",")

#Når den splitter hvad før var data typen "string", så kommer det tilbage som datatypen "list"

['It was the best of times', ' it was the worst of times']

In [9]:
#find datatype
type(text_snippet.split(","))

list

## Sequence types - lists

In [10]:
#define a list
colours = ["blue", "green", "red"]

#"" gør det til en string og så skal de adskilles af et komma, for at det bliver forskellige punkter på en liste

In [11]:
colours

['blue', 'green', 'red']

In [12]:
#finde datatypen af en specifik variable - her er det et punkt i listen
type(colours[1])

str

In [13]:
#Hvis man vil finde den sidste i listen
colours[-1]

#Det er -1 fordi man starter med 0 og den bevæger sig på en måde en cirkel, så for at finde den sidste på listen kan man bruge -1

'red'

In [14]:
user_data = ["mary", 42, 1.65]

In [15]:
big_list = [user_data, colours]

In [16]:
big_list

[['mary', 42, 1.65], ['blue', 'green', 'red']]

In [17]:
#opgave: find 42 gennem big_list variablen
big_list[0][1]

42

In [18]:
user_data + colours

['mary', 42, 1.65, 'blue', 'green', 'red']

In [19]:
#tilføj punkter til en liste
colours.append("yellow")

colours

['blue', 'green', 'red', 'yellow']

In [20]:
#Fjern et punkt fra listen
colours.remove("green")

In [21]:
colours.remove("yellow")
colours

['blue', 'red']

### Tuples

In [22]:
colours_tup =("blue", "green", "red")
#tuples er med () og strings er []

In [23]:
#strings og tuples er næsten ens, men den store forskel er at man ikke kan ændre på en tupæes, ligesom man kan på strings som ovenover
colours_tup

('blue', 'green', 'red')

### Maptypes or dictionaries

In [24]:
#Ross er stor fan af datatypen dictionaries
#Når man arbejder med distionaries så er det curlybrackets {}
user_ages = {"mary":42, "john":34}

In [25]:
user_ages["mary"]

42

In [26]:
new_users = dict(mary=dict(age=42, height=1.65),
                john=dict(age=50, height=1.80),
                alice=dict(age=24, height=1.83))

In [27]:
new_users["mary"]["age"]

42

### Number types

In [28]:
#Der findes to slags number types. 
#Den ene er interger(ints), som er hele tal, uden nogle decimaler
#Den anden er floating numbers, det er så tal der har decimaler

type(2)

int

In [29]:
type(2.1)

float

In [30]:
type(2.0)
#Det er stadig en float fordi der er et decimal, selvom at det bare er 0


float

In [31]:
#Man kan konvertere mellem int og floats
float(2)

2.0

In [32]:
int(2.7)

2

In [33]:
#Division will always return a float
10/2

5.0

In [34]:
#Med mindre man bruger to skråstreger
10//2

5

### Boolean (Bool) types

In [35]:
#Det er typisk true eller false, men svarene kan også komme tilbage som tal
True == 1

#hvor True er 1 og false er 0

True

# Introducing "numpy" arrays

In [36]:
#En package for Python der betyder Numerical Python - Det skal vist gøres hver gang
import numpy as np
import os

In [37]:
#How to load a file, first create a file path
filepath = os.path.join("..", "..", "cds-vis-data", "data", "sample-data", "sample-data-01.csv")

In [38]:
filepath

'../../cds-vis-data/data/sample-data/sample-data-01.csv'

In [39]:
#load the file
data = np.loadtxt(fname=filepath, delimiter=",")

In [40]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [41]:
type(data)

numpy.ndarray

In [42]:
data.dtype

dtype('float64')

In [43]:
data.shape

(60, 40)

In [44]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [45]:
#Finde en specifik value. Vi bevæger lodret og så vandret
data[0,0]

#At finde den i øverste venstre hjørne

0.0

In [46]:
data[-1,-1]
#at finde nederste højre hjørne

0.0

In [47]:
#array slice
data[0:4,0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [49]:
#select a whole row
data[0,:]

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [50]:
#select a whole column
data[:,0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
#Find an average score for something in the data
np.mean(data)

6.14875

In [52]:
np.max(data)

20.0

In [53]:
np.min(data)

0.0

In [54]:
#max value for hver række
np.max(data, axis=1)

array([18., 18., 19., 17., 17., 18., 17., 20., 17., 18., 18., 18., 17.,
       16., 17., 18., 19., 19., 17., 19., 19., 16., 17., 15., 17., 17.,
       18., 17., 20., 17., 16., 19., 15., 15., 19., 17., 16., 17., 19.,
       16., 18., 19., 16., 19., 18., 16., 19., 15., 16., 18., 14., 20.,
       17., 15., 17., 16., 17., 19., 18., 18.])

In [55]:
#max value for hvor kolonne
np.max(data, axis=0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 19., 18., 17., 16., 15.,
       14., 13., 12., 11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,
        1.])